### ISSUE TITLE
企业微信url回调总是不通过，有这方面配置的代码或者相关资料么？

### ISSUE THREAD

**Issue by yangli-os** [fanchunke/chatgpt-wecom#28]
企业微信url回调总是不通过，有这方面配置的代码或者相关资料么？

**Comment by fanchunke** [comment]
@yangli-os 看看服务的日志，有什么报错吗

**Comment by yangli-os** [comment]
是企业微信的那个url认证，需要一个get服务的吧？没有找到合适的代码在服务器部署get回调的服务

**Comment by fanchunke** [comment]
> 是企业微信的那个url认证，需要一个get服务的吧？没有找到合适的代码在服务器部署get回调的服务

@yangli-os 现有的代码中已经集成了企业微信回调的接口了，get 请求都是支持的。

**Comment by yangli-os** [comment]
<img width="649" alt="image" src="https://user-images.githubusercontent.com/47737324/222181537-a44ebc01-1d20-46ee-a097-10bce7b10990.png">
我使用自己的服务器地址部署，80端口作为服务端口，url填写有问题么？全程按照你的步骤下来的没有报错，但就是显示回调不成功

**Comment by fanchunke** [comment]
@yangli-os 服务部署后默认的地址是http://ip:port/wecom/receive，这个地址在文档上有写。如果自己做了代理转发的话，按照转发规则配置地址。

**Comment by yangli-os** [comment]
十分感谢，但我改为：http://8.209.245.143:80/wecom/receive也还是无法调通，我已经把地址改为80的端口了

**Comment by yangli-os** [comment]
并且我的http://8.209.245.143:80会显示404 page no found

**Comment by fanchunke** [comment]
@yangli-os 首先确认下docker服务开的端口，默认应该是8000，我看你使用的是80端口，是有代理从80端口转发到了8000端口吗

**Comment by yangli-os** [comment]
总算成功了，十分感谢，我以为只有配置文件一个地方有端口设置
