### ISSUE TITLE
如何与企业微信的机器人对接呢

### ISSUE THREAD

**Issue by neohob** [fanchunke/chatgpt-wecom#51]
自创应用已经成功，但是如何与企业微信中的机器人链接呢，我用机器人的webhook url 替代conf里面的url里面，得到结果就是: 响应失败，错误码：93000，错误原因：invalid webhook url

**Comment by alex7768** [comment]
我也想知道 怎么才能群聊

**Comment by fanchunke** [comment]
@neohob @alex7768 不支持群机器人。企业微信群机器人只支持主动向群里发送消息，不支持接收群成员@机器人的消息。
