### ISSUE TITLE
failed creating schema resources error="mysql: querying mysql version dial tcp 127.0.0.1:3306: connect: connection refused"

### ISSUE THREAD

**Issue by Jas0nxlee** [fanchunke/chatgpt-wecom#6]
2023-02-16T08:06:02Z FATAL  ../../../app/cmd/app/app.go:36 > failed creating schema resources error="mysql: querying mysql version dial tcp 127.0.0.1:3306: connect: connection refused"

**Comment by Jas0nxlee** [comment]
没有安装mysql。

**Comment by fanchunke** [comment]
@Jas0nxlee 对的，需要有数据库。后续会出一个版本，支持 sqlite，用于本地测试。

**Comment by Jas0nxlee** [comment]
已找到原因。online.conf内mysql的ip改为内网ip或已映射的公网ip，不要用127.0.0.1
[database]
dialect="mysql"
**host="127.0.0.1"** 
port=3306
user="root"
password="12345678"
dbname="chatgpt"

**Comment by fanchunke** [comment]
@Jas0nxlee 好的，那我先关闭 issue 了。
