### ISSUE TITLE
maxprocs: Leaving GOMAXPROCS=2: CPU quota undefined

### ISSUE THREAD

**Issue by Jas0nxlee** [fanchunke/chatgpt-wecom#7]
/home/works/program # ./app -conf=conf/online.conf -init-ent
2023/02/16 09:00:51 maxprocs: Leaving GOMAXPROCS=2: CPU quota undefined

**Comment by fanchunke** [comment]
@infoBrainSys @Jas0nxlee 这是初始化数据库表的命令，`maxprocs: Leaving GOMAXPROCS=2: CPU quota undefined` 没有啥问题，只要 `./app -conf=conf/online.conf -init-ent` 正常执行就可以了。

**Comment by Jas0nxlee** [comment]
> @infoBrainSys @Jas0nxlee 这是初始化数据库表的命令，`maxprocs: Leaving GOMAXPROCS=2: CPU quota undefined` 没有啥问题，只要 `./app -conf=conf/online.conf -init-ent` 正常执行就可以了。

提示这个之后，就返回命令行了。应该是没有继续正常执行。

**Comment by Jas0nxlee** [comment]
可以关闭了，此提示不影响后续，经检查mysql数据初始化已经完成

**Comment by infoBrainSys** [comment]
> 可以关闭了，此提示不影响后续，经检查mysql数据初始化已经完成

已正常运行
