### ISSUE TITLE
error="CreateCompletion failed: error, status code: 400, message:

### ISSUE THREAD

**Issue by chanche81** [fanchunke/chatgpt-wecom#8]
`ERROR  ../../../app/internal/api/receive.go:43 > Get GPT Response error: CreateCompletion failed: error, status code: 400, message: This model's maximum context length is 4097 tokens, however you requested 4289 tokens (2789 in your prompt; 1500 for the completion). Please reduce your prompt; or completion length. error="CreateCompletion failed: error, status code: 400, message: This model's maximum context length is 4097 tokens, however you requested 4289 tokens (2789 in your prompt; 1500 for the completion). Please reduce your prompt; or completion length."`

请问下会话过长了怎么关闭重新再起一个

**Comment by fanchunke** [comment]
@chanche81 目前是拿了最近10轮的对话去请求接口的，如果超过最大长度会报错。可以多问几次短对话，后续会正常。后续会再优化一下这里的逻辑，再增加一个命令用于重启会话。

**Comment by chanche81** [comment]
感谢及时回答。  增加一个重启会话功能，对于大文本量很有必要。谢谢

**Comment by biglazy** [comment]
出现了同样的问题，输入任何对话，看起来都会附加一堆不知道哪来的文字，导致超长了。 

![image](https://user-images.githubusercontent.com/466591/219533376-d24df6dd-b0d8-46fe-86fe-25eb3939e855.png)

**Comment by fanchunke** [comment]
@biglazy 抱歉，回复有点晚。目前为了能支持多轮对话，所以每次发送请求前，就会带着之前和机器人的会话，这样机器人能根据整个上下文给出比较符合语境的回答。

**Comment by fanchunke** [comment]
@chanche81 @biglazy 新版本已经支持会话重启，欢迎试用。

**Comment by chanche81** [comment]
@fanchunke 感谢，试用了，挺好用。有了restart ，可以手动结束会话。   赞
