### ISSUE TITLE
这个机器人傻傻的，不能像 chatgpt 一样根据要求返回代码

### ISSUE THREAD

**Issue by albertofwb** [fanchunke/chatgpt-wecom#9]
![image](https://user-images.githubusercontent.com/5900716/219426674-f2968d92-a789-4ed3-a105-898e61800cf2.png)

**Comment by zhu0629** [comment]
api接口的是比较傻的, web版的要好很多.

**Comment by albertofwb** [comment]
最新代码似乎解决了问题，可以为我生成代码啦
